Traceback (most recent call last):
  File "/usr/share/miniconda/envs/CrocoDash/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda/envs/CrocoDash/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/CrocoDash/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/CrocoDash/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/CrocoDash/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/CrocoDash/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/CrocoDash/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/CrocoDash/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
case.configure_forcings(
    date_range = ["2020-01-01 00:00:00", "2020-01-09 00:00:00"],
    tidal_constituents = ['M2'],
    tpxo_elevation_filepath = "s3://crocodile-cesm/CrocoDash/data/tpxo/h_tpxo9.v1.zarr/",
    tpxo_velocity_filepath = "s3://crocodile-cesm/CrocoDash/data/tpxo/u_tpxo9.v1.zarr/"
)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 0>[0;34m()[0m
[0;32m----> 1[0m [38;5;28;43;01mcase[39;49;00m[38;5;241m.[39mconfigure_forcings(
[1;32m      2[0m     date_range [38;5;241m=[39m [[38;5;124m"[39m[38;5;124m2020-01-01 00:00:00[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m2020-01-09 00:00:00[39m[38;5;124m"[39m],
[1;32m      3[0m     tidal_constituents [38;5;241m=[39m [[38;5;124m'[39m[38;5;124mM2[39m[38;5;124m'[39m],
[1;32m      4[0m     tpxo_elevation_filepath [38;5;241m=[39m [38;5;124m"[39m[38;5;124ms3://crocodile-cesm/CrocoDash/data/tpxo/h_tpxo9.v1.zarr/[39m[38;5;124m"[39m,
[1;32m      5[0m     tpxo_velocity_filepath [38;5;241m=[39m [38;5;124m"[39m[38;5;124ms3://crocodile-cesm/CrocoDash/data/tpxo/u_tpxo9.v1.zarr/[39m[38;5;124m"[39m
[1;32m      6[0m )

[0;31mNameError[0m: name 'case' is not defined

